### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by RalfJung** [rust-rfcs/const-eval#23]
The README.md of this repo links to https://rust-lang-nursery.github.io/rustc-guide/const-eval.html, which is a dead link.

**Comment by RalfJung** [comment]
https://rust-lang-nursery.github.io/rustc-guide/mir/index.html is dead, too. Looks like some global search-and-replace is needed?

Ideally, we'd also get redirects. Killing all rustc-guide links isn't great...

**Comment by oli-obk** [comment]
The links have been adjusted
