### ISSUE TITLE
Constants and interior mutability

### ISSUE THREAD

**Issue by RalfJung** [rust-rfcs/const-eval#5]
According to @oli-obk, there are currently some checks somewhere to rule out interior mutability in constants. However, this is accepted:
```rust
use std::sync::atomic::AtomicUsize;
const FOO : AtomicUsize = AtomicUsize::new(3);
```
It would be great if the reasons for this check could be spelled out, ideally somewhere in this repo :D

**Comment by oli-obk** [comment]
Interior mutability is ruled out in statics, not in constants. Constants are annotated internally so statics using them know about it

**Comment by RalfJung** [comment]
This works as well:
```rust
use std::sync::atomic::AtomicUsize;
static FOO : AtomicUsize = AtomicUsize::new(3);
```
And indeed why would it not...

**Comment by oli-obk** [comment]
discussion continued in https://github.com/rust-lang/rust/issues/53819
